# Generated by Django 4.1 on 2022-09-08 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigblog',
            name='dete',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bigblog',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bigblog',
            name='image',
            field=models.ImageField(blank='True', null='True', upload_to='medie'),
        ),
        migrations.AlterField(
            model_name='bigblog',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
