# Generated by Django 4.1 on 2022-09-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_bigblog_dete_bigblog_update_alter_bigblog_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_L',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100, unique=True)),
                ('blog_dcs', models.TextField()),
                ('blog_image', models.ImageField(blank='True', null='True', upload_to='medie')),
                ('blog_dete', models.DateTimeField(auto_now_add=True)),
                ('blog_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
